# Generated by Django 5.0.1 on 2024-02-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_github_url_remove_profile_twitter_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='m_bio',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='m_email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='facebook_url',
            new_name='m_facebook_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='m_profile_pic',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='m_user',
        ),
    ]
