# Generated by Django 5.0.1 on 2024-02-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('m_isSuccess', models.BooleanField(default=False)),
                ('m_order_id', models.CharField(default='', max_length=10)),
                ('m_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
