# Generated by Django 5.0.1 on 2024-02-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_paymentmodel_m_timestamp_paymentmodel_m_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_order_id', models.CharField(max_length=50, unique=True)),
                ('o_items', models.TextField()),
                ('o_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('o_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
