# Generated by Django 5.0.1 on 2024-02-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderModel',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='o_items',
            new_name='m_items',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='o_notes',
            new_name='m_notes',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='o_order_id',
            new_name='m_order_id',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='o_total_amount',
            new_name='m_total_amount',
        ),
    ]
