# Generated by Django 5.0.1 on 2024-02-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_order_ordermodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='m_card_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
