# Generated by Django 5.0.1 on 2024-02-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprovider',
            name='contact_details',
            field=models.CharField(help_text='Contact details of the delivery provider', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryprovider',
            name='name',
            field=models.CharField(help_text='Name of the delivery provider', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the delivery request was created'),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='delivery_destination',
            field=models.CharField(help_text='Destination where the package will be delivered', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='pickup_location',
            field=models.CharField(help_text='Location from where the package will be picked up', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='preferred_delivery_window',
            field=models.CharField(blank=True, help_text='Preferred time window for delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='size_weight',
            field=models.CharField(help_text='Size and weight of the package', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Any special instructions for delivery'),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('In transit', 'In transit'), ('Delivered', 'Delivered')], default='pending', help_text='Status of the delivery request', max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the delivery request was last updated'),
        ),
    ]
