# Generated by Django 5.0.1 on 2024-02-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_deliveryprovider_contact_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryprovider',
            old_name='contact_details',
            new_name='m_contact_details',
        ),
        migrations.RenameField(
            model_name='deliveryprovider',
            old_name='name',
            new_name='m_name',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='created_at',
            new_name='m_created_at',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='delivery_destination',
            new_name='m_delivery_destination',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='pickup_location',
            new_name='m_pickup_location',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='preferred_delivery_window',
            new_name='m_preferred_delivery_window',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='size_weight',
            new_name='m_size_weight',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='special_instructions',
            new_name='m_special_instructions',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='status',
            new_name='m_status',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='updated_at',
            new_name='m_updated_at',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='user',
            new_name='m_user',
        ),
    ]
