# Generated by Django 5.0.1 on 2024-02-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_rename_contact_details_deliveryprovider_m_contact_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryprovider',
            old_name='m_contact_details',
            new_name='contact_details',
        ),
        migrations.RenameField(
            model_name='deliveryprovider',
            old_name='m_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='m_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='m_delivery_destination',
            new_name='delivery_destination',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='m_pickup_location',
            new_name='pickup_location',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='m_preferred_delivery_window',
            new_name='preferred_delivery_window',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='m_size_weight',
            new_name='size_weight',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='m_special_instructions',
            new_name='special_instructions',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='m_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='m_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='m_user',
            new_name='user',
        ),
    ]
