# Generated by Django 4.1.1 on 2024-02-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rentApproval', '0002_renter'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_rentApproval.product')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_rentApproval.renter')),
            ],
        ),
    ]
