# Generated by Django 4.1.1 on 2024-02-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rentApproval', '0003_renterproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='rental_price',
        ),
    ]
