# Generated by Django 4.1.1 on 2024-02-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rentApproval', '0004_rename_price_product_rental_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='renterproduct',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
