# Generated by Django 4.1.1 on 2024-02-16 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rentApproval', '0007_alter_renterproduct_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=255)),
                ('m_description', models.TextField()),
                ('m_rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('m_quantity_available', models.IntegerField(default=0)),
                ('m_created_at', models.DateTimeField(auto_now_add=True)),
                ('m_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RenterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_username', models.CharField(max_length=255)),
                ('m_password', models.CharField(max_length=255)),
                ('m_email', models.EmailField(max_length=254)),
                ('m_address', models.TextField()),
                ('m_phone_number', models.CharField(max_length=20)),
                ('m_created_at', models.DateTimeField(auto_now_add=True)),
                ('m_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RenterProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_approved_at', models.DateTimeField(blank=True, null=True)),
                ('m_is_approved', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=20)),
                ('m_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_rentApproval.productmodel')),
                ('m_renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_rentApproval.rentermodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='renterproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='renterproduct',
            name='renter',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Renter',
        ),
        migrations.DeleteModel(
            name='RenterProduct',
        ),
    ]
