# Generated by Django 4.1.1 on 2024-02-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rentApproval', '0008_productmodel_rentermodel_renterproductmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenteeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_username', models.CharField(max_length=255)),
                ('m_password', models.CharField(max_length=255)),
                ('m_email', models.EmailField(max_length=254)),
                ('m_address', models.TextField()),
                ('m_phone_number', models.CharField(max_length=20)),
                ('m_created_at', models.DateTimeField(auto_now_add=True)),
                ('m_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
